const IngredientRoutes = require('./Ingredient');
const FoodRoutes = require('./Food');
const AuthRoutes = require('./Auth');
const RecipeRoutes = require('./Recipe');
const TableRoutes = require('./Table');
const CategoryRoutes = require('./Category');
const AreaRoutes = require('./Area');
const CustomerRoutes = require('./Customer');
const OrderRoutes = require('./Order');
const OrderDetailRoutes = require('./OrderDetail');
const StaffRoutes = require('./Staff');
const PaymentTransactionRoutes = require('./PaymentTransaction');
const PromotionRoutes = require('./Promotion');
const UploadRoutes = require("./Upload");

const Router = (app) => {
    app.use('/api/ingredients', IngredientRoutes);
    app.use('/api/foods', FoodRoutes);
    app.use('/api/auth', AuthRoutes);
    app.use('/api/recipes', RecipeRoutes);
    app.use('/api/tables', TableRoutes);
    app.use('/api/categories', CategoryRoutes);
    app.use('/api/customer', CustomerRoutes);
    app.use('/api/areas', AreaRoutes);
    app.use('/api/staffs', StaffRoutes);
    app.use('/api/orders', OrderRoutes);
    app.use('/api/order-details', OrderDetailRoutes);
    app.use('/api/payment-transactions', PaymentTransactionRoutes);
    app.use('/api/promotions', PromotionRoutes);
    app.use("/api/uploads", UploadRoutes);
};
module.exports = Router;